services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  web:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@localhost:5432/flaskdb
      
    ports:
      - "5000:5000"
    command: ["sh", "-c", "flask db upgrade && flask run --host=0.0.0.0"]
    volumes:
      - .:/app

volumes:
  postgres_data: